import { HttpClient, HttpClientModule } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';

@Injectable({
  providedIn: 'root'
})
export class WeatherService {

  constructor(private http:HttpClient) { }

  getWeather(cityName:string):Observable<any> {
    return this.http.get(`https://api.openweathermap.org/data/2.5/weather?q=${cityName}&appid=e520eaa6fce77e8d32bda94a19e2ad36&units=metric`)
  }
  
  countryCityData: { [key: string]: string[] } = {
    'Afghanistan': ['Kabul', 'Kandahar', 'Herat', 'Mazar-i-Sharif'],
    'Albania': ['Tirana', 'Durrës', 'Vlorë', 'Shkodër'],
    'Algeria': ['Algiers', 'Oran', 'Constantine', 'Annaba'],
    'Andorra': ['Andorra la Vella', 'Escaldes-Engordany', 'Encamp', 'La Massana'],
    'Angola': ['Luanda', 'Huambo', 'Lobito', 'Benguela'],
    'Argentina': ['Buenos Aires', 'Córdoba', 'Rosario', 'Mendoza'],
    'Armenia': ['Yerevan', 'Gyumri', 'Vanadzor', 'Hrazdan'],
    'Australia': ['Sydney', 'Melbourne', 'Brisbane', 'Perth'],
    'Austria': ['Vienna', 'Graz', 'Linz', 'Salzburg'],
    'Azerbaijan': ['Baku', 'Ganja', 'Sumqayit', 'Mingachevir'],
    'Bahamas': ['Nassau', 'Freeport', 'West End', 'Coopers Town'],
    'Bahrain': ['Manama', 'Riffa', 'Muharraq', 'Hamad Town'],
    'Bangladesh': ['Dhaka', 'Chittagong', 'Khulna', 'Rajshahi'],
    'Barbados': ['Bridgetown', 'Speightstown', 'Oistins', 'Holetown'],
    'Belarus': ['Minsk', 'Gomel', 'Mogilev', 'Vitebsk'],
    'Belgium': ['Brussels', 'Antwerp', 'Ghent', 'Charleroi'],
    'Belize': ['Belize City', 'San Ignacio', 'Orange Walk', 'Belmopan'],
    'Benin': ['Cotonou', 'Porto-Novo', 'Parakou', 'Djougou'],
    'Bhutan': ['Thimphu', 'Phuntsholing', 'Punakha', 'Gelephu'],
    'Bolivia': ['La Paz', 'Santa Cruz', 'Cochabamba', 'Sucre'],
    'Bosnia and Herzegovina': ['Sarajevo', 'Banja Luka', 'Tuzla', 'Mostar'],
    'Botswana': ['Gaborone', 'Francistown', 'Molepolole', 'Maun'],
    'Brazil': ['São Paulo', 'Rio de Janeiro', 'Brasília', 'Salvador'],
    'Brunei': ['Bandar Seri Begawan', 'Kuala Belait', 'Seria', 'Tutong'],
    'Bulgaria': ['Sofia', 'Plovdiv', 'Varna', 'Burgas'],
    'Burkina Faso': ['Ouagadougou', 'Bobo-Dioulasso', 'Koudougou', 'Banfora'],
    'Burundi': ['Bujumbura', 'Gitega', 'Ngozi', 'Ruyigi'],
    'Cabo Verde': ['Praia', 'Mindelo', 'Santa Maria', 'Espargos'],
    'Cambodia': ['Phnom Penh', 'Siem Reap', 'Battambang', 'Sihanoukville'],
    'Cameroon': ['Douala', 'Yaoundé', 'Garoua', 'Bamenda'],
    'Canada': ['Toronto', 'Vancouver', 'Montreal', 'Calgary'],
    'Central African Republic': ['Bangui', 'Bimbo', 'Berbérati', 'Carnot'],
    'Chad': ["N'Djamena", 'Moundou', 'Sarh', 'Abeche'],
    'Chile': ['Santiago', 'Valparaíso', 'Concepción', 'La Serena'],
    'China': ['Beijing', 'Shanghai', 'Guangzhou', 'Shenzhen'],
    'Colombia': ['Bogotá', 'Medellín', 'Cali', 'Barranquilla'],
    'Comoros': ['Moroni', 'Mutsamudu', 'Fomboni', 'Domoni'],
    'Congo': ['Kinshasa', 'Lubumbashi', 'Mbuji-Mayi', 'Kananga'],
    'Congo-Brazzaville': ['Brazzaville', 'Pointe-Noire', 'Dolisie', 'Nkayi'],
    'Costa Rica': ['San José', 'Alajuela', 'Heredia', 'Cartago'],
    'Croatia': ['Zagreb', 'Split', 'Rijeka', 'Osijek'],
    'Cuba': ['Havana', 'Santiago de Cuba', 'Camagüey', 'Holguín'],
    'Cyprus': ['Nicosia', 'Limassol', 'Larnaca', 'Famagusta'],
    'Czech Republic': ['Prague', 'Brno', 'Ostrava', 'Pilsen'],
    'Denmark': ['Copenhagen', 'Aarhus', 'Odense', 'Aalborg'],
    'Djibouti': ['Djibouti', 'Ali Sabieh', 'Tadjoura', 'Dikhil'],
    'Dominica': ['Roseau', 'Portsmouth', 'Marigot', 'Berekua'],
    'Dominican Republic': ['Santo Domingo', 'Santiago', 'La Vega', 'San Pedro de Macorís'],
    'Ecuador': ['Quito', 'Guayaquil', 'Cuenca', 'Santo Domingo'],
    'Egypt': ['Cairo', 'Alexandria', 'Giza', 'Shubra El Kheima'],
    'El Salvador': ['San Salvador', 'Santa Ana', 'San Miguel', 'Mejicanos'],
    'Equatorial Guinea': ['Malabo', 'Bata', 'Ebebiyin', 'Aconibe'],
    'Eritrea': ['Asmara', 'Keren', 'Massawa', 'Mendefera'],
    'Estonia': ['Tallinn', 'Tartu', 'Narva', 'Pärnu'],
    'Eswatini': ['Mbabane', 'Manzini', 'Big Bend', 'Malkerns'],
    'Ethiopia': ['Addis Ababa', 'Dire Dawa', 'Mekelle', 'Adama'],
    'Fiji': ['Suva', 'Nadi', 'Lautoka', 'Labasa'],
    'Finland': ['Helsinki', 'Espoo', 'Tampere', 'Vantaa'],
    'France': ['Paris', 'Marseille', 'Lyon', 'Toulouse'],
    'Gabon': ['Libreville', 'Port-Gentil', 'Franceville', 'Oyem'],
    'Gambia': ['Banjul', 'Serekunda', 'Brikama', 'Bakau'],
    'Georgia': ['Tbilisi', 'Kutaisi', 'Batumi', 'Rustavi'],
    'Germany': ['Berlin', 'Hamburg', 'Munich', 'Cologne'],
    'Ghana': ['Accra', 'Kumasi', 'Tamale', 'Takoradi'],
    'Greece': ['Athens', 'Thessaloniki', 'Patras', 'Heraklion'],
    'Grenada': ['St. George\'s', 'Gouyave', 'Grenville', 'Victoria'],
    'Guatemala': ['Guatemala City', 'Mixco', 'Villa Nueva', 'Quetzaltenango'],
    'Guinea': ['Conakry', 'Kankan', 'Nzérékoré', 'Kindia'],
    'Guinea-Bissau': ['Bissau', 'Bafatá', 'Gabú', 'Bissorã'],
    'Guyana': ['Georgetown', 'Linden', 'New Amsterdam', 'Anna Regina'],
    'Haiti': ['Port-au-Prince', 'Cap-Haïtien', 'Gonaïves', 'Carrefour'],
    'Honduras': ['Tegucigalpa', 'San Pedro Sula', 'Choloma', 'La Ceiba'],
    'Hungary': ['Budapest', 'Debrecen', 'Szeged', 'Miskolc'],
    'Iceland': ['Reykjavík', 'Kopavogur', 'Hafnarfjordur', 'Akureyri'],
    'India': ['Mumbai', 'Delhi', 'Bangalore', 'Hyderabad'],
    'Indonesia': ['Jakarta', 'Surabaya', 'Bandung', 'Medan'],
    'Iran': ['Tehran', 'Mashhad', 'Isfahan', 'Karaj'],
    'Iraq': ['Baghdad', 'Basra', 'Mosul', 'Erbil'],
    'Ireland': ['Dublin', 'Cork', 'Limerick', 'Galway'],
    'Israel': ['Jerusalem', 'Tel Aviv', 'Haifa', 'Rishon LeZion'],
    'Italy': ['Rome', 'Milan', 'Naples', 'Turin'],
    'Jamaica': ['Kingston', 'Montego Bay', 'Spanish Town', 'Portmore'],
    'Japan': ['Tokyo', 'Osaka', 'Nagoya', 'Sapporo'],
    'Jordan': ['Amman', 'Irbid', 'Zarqa', 'Aqaba'],
    'Kazakhstan': ['Almaty', 'Nur-Sultan', 'Shymkent', 'Karaganda'],
    'Kenya': ['Nairobi', 'Mombasa', 'Kisumu', 'Nakuru'],
    'Kiribati': ['Tarawa', 'Betio', 'Bikenibeu', 'Bairiki'],
    'Korea, North': ['Pyongyang', 'Hamhung', 'Nampo', 'Sunchon'],
    'Korea, South': ['Seoul', 'Busan', 'Incheon', 'Daegu'],
    'Kuwait': ['Kuwait City', 'Al Ahmadi', 'Hawalli', 'Al Farwaniyah'],
    'Kyrgyzstan': ['Bishkek', 'Osh', 'Jalal-Abad', 'Karakol'],
    'Laos': ['Vientiane', 'Luang Prabang', 'Savannakhet', 'Pakse'],
    'Latvia': ['Riga', 'Daugavpils', 'Liepaja', 'Jelgava'],
    'Lebanon': ['Beirut', 'Tripoli', 'Sidon', 'Tyre'],
    'Lesotho': ['Maseru', 'Teyateyaneng', 'Mafeteng', 'Hlotse'],
    'Liberia': ['Monrovia', 'Gbarnga', 'Kakata', 'Bensonville'],
    'Libya': ['Tripoli', 'Benghazi', 'Misrata', 'Bayda'],
    'Liechtenstein': ['Vaduz', 'Schaan', 'Balzers', 'Triesen'],
    'Lithuania': ['Vilnius', 'Kaunas', 'Klaipeda', 'Šiauliai'],
    'Luxembourg': ['Luxembourg City', 'Esch-sur-Alzette', 'Differdange', 'Dudelange'],
    'Madagascar': ['Antananarivo', 'Toamasina', 'Antsirabe', 'Fianarantsoa'],
    'Malawi': ['Lilongwe', 'Blantyre', 'Mzuzu', 'Zomba'],
    'Malaysia': ['Kuala Lumpur', 'George Town', 'Johor Bahru', 'Ipoh'],
    'Maldives': ['Malé', 'Hulhumalé', 'Fuvahmulah', 'Thinadhoo'],
    'Mali': ['Bamako', 'Sikasso', 'Mopti', 'Koulikoro'],
    'Malta': ['Valletta', 'Birkirkara', 'Mosta', 'Qormi'],
    'Marshall Islands': ['Majuro', 'Ebeye', 'Rairok', 'Laura'],
    'Mauritania': ['Nouakchott', 'Nouadhibou', 'Rosso', 'Kaédi'],
    'Mauritius': ['Port Louis', 'Beau Bassin-Rose Hill', 'Vacoas-Phoenix', 'Curepipe'],
    'Mexico': ['Mexico City', 'Guadalajara', 'Monterrey', 'Puebla'],
    'Micronesia': ['Palikir', 'Weno', 'Kolonia', 'Tofol'],
    'Moldova': ['Chișinău', 'Tiraspol', 'Bălți', 'Bender'],
    'Monaco': ['Monaco', 'Monte Carlo', 'La Condamine', 'Fontvieille'],
    'Mongolia': ['Ulaanbaatar', 'Erdenet', 'Darkhan', 'Choibalsan'],
    'Montenegro': ['Podgorica', 'Nikšić', 'Herceg Novi', 'Pljevlja'],
    'Morocco': ['Rabat', 'Casablanca', 'Marrakesh', 'Tangier'],
    'Mozambique': ['Maputo', 'Matola', 'Beira', 'Nampula'],
    'Myanmar': ['Yangon', 'Mandalay', 'Naypyidaw', 'Mawlamyine'],
    'Namibia': ['Windhoek', 'Rundu', 'Walvis Bay', 'Swakopmund'],
    'Nauru': ['Yaren', 'Boe', 'Aiwo', 'Anabar'],
    'Nepal': ['Kathmandu', 'Pokhara', 'Lalitpur', 'Biratnagar'],
    'Netherlands': ['Amsterdam', 'Rotterdam', 'The Hague', 'Utrecht'],
    'New Zealand': ['Auckland', 'Wellington', 'Christchurch', 'Hamilton'],
    'Nicaragua': ['Managua', 'León', 'Masaya', 'Matagalpa'],
    'Niger': ['Niamey', 'Zinder', 'Maradi', 'Tahoua'],
    'Nigeria': ['Lagos', 'Abuja', 'Kano', 'Ibadan'],
    'North Macedonia': ['Skopje', 'Bitola', 'Kumanovo', 'Tetovo'],
    'Norway': ['Oslo', 'Bergen', 'Trondheim', 'Stavanger'],
    'Oman': ['Muscat', 'Salalah', 'Sohar', 'Nizwa'],
    'Pakistan': ['Karachi', 'Lahore', 'Faisalabad', 'Rawalpindi'],
    'Palau': ['Ngerulmud', 'Koror', 'Melekeok', 'Airai'],
    'Palestine': ['Gaza', 'Hebron', 'Jabalia', 'Nablus'],
    'Panama': ['Panama City', 'San Miguelito', 'Colón', 'David'],
    'Papua New Guinea': ['Port Moresby', 'Lae', 'Mount Hagen', 'Madang'],
    'Paraguay': ['Asunción', 'Ciudad del Este', 'San Lorenzo', 'Luque'],
    'Peru': ['Lima', 'Arequipa', 'Trujillo', 'Chiclayo'],
    'Philippines': ['Manila', 'Quezon City', 'Caloocan', 'Davao City'],
    'Poland': ['Warsaw', 'Kraków', 'Łódź', 'Wrocław'],
    'Portugal': ['Lisbon', 'Porto', 'Amadora', 'Braga'],
    'Qatar': ['Doha', 'Al Rayyan', 'Umm Salal Muhammad', 'Al Wakrah'],
    'Romania': ['Bucharest', 'Cluj-Napoca', 'Timișoara', 'Iași'],
    'Russia': ['Moscow', 'Saint Petersburg', 'Novosibirsk', 'Yekaterinburg'],
    'Rwanda': ['Kigali', 'Butare', 'Gitarama', 'Ruhengeri'],
    'Saint Kitts and Nevis': ['Basseterre', 'Charlestown', 'Sandy Point Town', 'Cayon'],
    'Saint Lucia': ['Castries', 'Gros Islet', 'Vieux Fort', 'Micoud'],
    'Saint Vincent and the Grenadines': ['Kingstown', 'Georgetown', 'Barrouallie', 'Chateaubelair'],
    'Samoa': ['Apia', 'Vaitele', 'Faleula', 'Siusega'],
    'San Marino': ['San Marino', 'Serravalle', 'Borgo Maggiore', 'Domagnano'],
    'Sao Tome and Principe': ['São Tomé', 'Santo Amaro', 'Neves', 'Trindade'],
    'Saudi Arabia': ['Riyadh', 'Jeddah', 'Mecca', 'Medina'],
    'Senegal': ['Dakar', 'Pikine', 'Touba', 'Thiès'],
    'Serbia': ['Belgrade', 'Novi Sad', 'Niš', 'Kragujevac', 'Pristina'],
    'Seychelles': ['Victoria', 'Anse Boileau', 'Anse Royale', 'Cascade'],
    'Sierra Leone': ['Freetown', 'Bo', 'Kenema', 'Makeni'],
    'Singapore': ['Singapore'],
    'Slovakia': ['Bratislava', 'Košice', 'Prešov', 'Žilina'],
    'Slovenia': ['Ljubljana', 'Maribor', 'Celje', 'Kranj'],
    'Solomon Islands': ['Honiara', 'Gizo', 'Auki', 'Tulaghi'],
    'Somalia': ['Mogadishu', 'Hargeisa', 'Berbera', 'Kismayo'],
    'South Africa': ['Johannesburg', 'Cape Town', 'Durban', 'Pretoria'],
    'South Sudan': ['Juba', 'Malakal', 'Wau', 'Yambio'],
    'Spain': ['Madrid', 'Barcelona', 'Valencia', 'Seville'],
    'Sri Lanka': ['Colombo', 'Kandy', 'Galle', 'Jaffna'],
    'Sudan': ['Khartoum', 'Omdurman', 'Nyala', 'Port Sudan'],
    'Suriname': ['Paramaribo', 'Lelydorp', 'Nieuw Nickerie', 'Moengo'],
    'Sweden': ['Stockholm', 'Gothenburg', 'Malmö', 'Uppsala'],
    'Switzerland': ['Zurich', 'Geneva', 'Basel', 'Lausanne'],
    'Syria': ['Damascus', 'Aleppo', 'Homs', 'Latakia'],
    'Taiwan': ['Taipei', 'Kaohsiung', 'Taichung', 'Tainan'],
    'Tajikistan': ['Dushanbe', 'Khujand', 'Kulob', 'Bokhtar'],
    'Tanzania': ['Dar es Salaam', 'Dodoma', 'Mwanza', 'Arusha'],
    'Thailand': ['Bangkok', 'Chiang Mai', 'Pattaya', 'Phuket'],
    'Timor-Leste': ['Dili', 'Baucau', 'Maliana', 'Suai'],
    'Togo': ['Lomé', 'Sokodé', 'Kara', 'Atakpamé'],
    'Tonga': ['Nukuʻalofa', 'Neiafu', 'Vaini', 'Haveluloto'],
    'Trinidad and Tobago': ['Port of Spain', 'San Fernando', 'Chaguanas', 'Arima'],
    'Tunisia': ['Tunis', 'Sfax', 'Sousse', 'Ettadhamen'],
    'Turkey': ['Istanbul', 'Ankara', 'Izmir', 'Bursa'],
    'Turkmenistan': ['Ashgabat', 'Turkmenabat', 'Dashoguz', 'Mary'],
    'Tuvalu': ['Funafuti', 'Fongafale', 'Savave', 'Tanrake'],
    'Uganda': ['Kampala', 'Gulu', 'Lira', 'Mbarara'],
    'Ukraine': ['Kyiv', 'Kharkiv', 'Odessa', 'Dnipro'],
    'United Arab Emirates': ['Dubai', 'Abu Dhabi', 'Sharjah', 'Al Ain'],
    'UK': ['London', 'Birmingham', 'Glasgow', 'Liverpool'],
    'USA': ['New York City', 'Los Angeles', 'Chicago', 'Houston'],
    'Uruguay': ['Montevideo', 'Salto', 'Paysandú', 'Las Piedras'],
    'Uzbekistan': ['Tashkent', 'Samarkand', 'Bukhara', 'Namangan'],
    'Vanuatu': ['Port Vila', 'Luganville', 'Norsup', 'Isangel'],
    'Vatican City': ['Vatican City'],
    'Venezuela': ['Caracas', 'Maracaibo', 'Valencia', 'Barquisimeto'],
    'Vietnam': ['Hanoi', 'Ho Chi Minh City', 'Da Nang', 'Hai Phong'],
    'Yemen': ['Sana\'a', 'Aden', 'Taiz', 'Ibb'],
    'Zambia': ['Lusaka', 'Kitwe', 'Ndola', 'Kabwe'],
    'Zimbabwe': ['Harare', 'Bulawayo', 'Chitungwiza', 'Mutare']
  };

  selectedCountry: string;
  countryData:any
}
